import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Excalidraw,exportToBlob,convertToExcalidrawElements} from '@excalidraw/excalidraw';
import '@excalidraw/excalidraw/index.css';
import MarkdownIt from 'markdown-it';
import DOMPurify from 'dompurify';
import katex from 'katex';
import 'katex/dist/katex.min.css';
import './style.css';
const data=JSON.parse(document.getElementById('lab-data').textContent);
const md=new MarkdownIt({html:false,linkify:false,breaks:true});
md.inline.ruler.after('escape','math',(s,silent)=>{if(s.src[s.pos]!=='$'||s.src[s.pos+1]==='$')return false;const end=s.src.indexOf('$',s.pos+1);if(end<0)return false;if(!silent){const t=s.push('math','',0);t.content=s.src.slice(s.pos+1,end);}s.pos=end+1;return true;});
md.block.ruler.before('fence','mathblock',(s,start,end,silent)=>{let from=s.bMarks[start]+s.tShift[start],to=s.eMarks[start];if(!s.src.slice(from,to).startsWith('$$'))return false;let content=s.src.slice(from+2,to),line=start;if(!content.endsWith('$$')){content+='\n';while(++line<end){const row=s.src.slice(s.bMarks[line],s.eMarks[line]);if(row.endsWith('$$')){content+=row;break;}content+=row+'\n';}if(line>=end)return false;}if(silent)return true;const t=s.push('mathblock','',0);t.content=content.slice(0,-2);s.line=line+1;return true;});
md.renderer.rules.math=(ts,i)=>katex.renderToString(ts[i].content,{throwOnError:false,trust:false});
md.renderer.rules.mathblock=(ts,i)=>katex.renderToString(ts[i].content,{throwOnError:false,trust:false,displayMode:true});
function Markdown({text=''}){return <div className="markdown" dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(md.render(text),{ADD_TAGS:['annotation'],FORBID_TAGS:['img']})}}/>;}
const download=(name,obj)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const readData=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});
const timefmt=n=>`${Math.floor(n/3600).toString().padStart(2,'0')}:${Math.floor(n/60%60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
const blank=a=>!a.markdown.trim()&&!(a.scene?.elements||[]).some(e=>!e.isDeleted)&&!a.attachments?.length;
function Lightbox({src,close}){return src&&<div className="lightbox" role="dialog" aria-label="放大图片" onClick={close}><button onClick={close}>关闭</button><img src={src}/></div>;}
function Exam(){
 const key='soft-exam-lab:'+data.state.attempt_id;
 const backup=(()=>{try{return JSON.parse(localStorage.getItem(key));}catch{return null;}})();
 const initial=data.offline&&backup?.attempt_id===data.state.attempt_id?backup:data.state;
 const [state,setState]=useState(initial),[answers,setAnswers]=useState(initial.answers),[idx,setIdx]=useState(0),[preview,setPreview]=useState(false),[draw,setDraw]=useState(false),[notice,setNotice]=useState(data.offline?'离线模式：仅浏览器草稿；交卷后必须导出并由 Agent 导入':'已读取本地记录'),[zoom,setZoom]=useState(null),[tick,setTick]=useState(Date.now()/1000),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
 const entries=data.pack.cases.flatMap(c=>c.questions.map(q=>({c,q}))),{c,q}=entries[idx];
 const current=useRef(state),ans=useRef(answers),api=useRef(null),dirty=useRef(false),chain=useRef(Promise.resolve()),generation=useRef(0),snapper=useRef(null);
 current.current=state;ans.current=answers;
 const assign=s=>{current.current=s;setState(s);};
 const change=a=>{dirty.current=true;generation.current++;ans.current=a;setAnswers(a);try{localStorage.setItem(key,JSON.stringify({...current.current,answers:a}));}catch{setNotice('浏览器备份空间不足；请保存或导出输入');}};
 async function snapshot(){const all={...ans.current};const view=api.current;if(view&&draw){const elements=view.getSceneElements();const appState=view.getAppState();const files=view.getFiles();const scene={elements,appState:{viewBackgroundColor:appState.viewBackgroundColor,zoom:appState.zoom,scrollX:appState.scrollX,scrollY:appState.scrollY},files};let png=null;if(elements.some(e=>!e.isDeleted)){const blob=await exportToBlob({elements,appState:{...appState,exportBackground:true},files,mimeType:'image/png',maxWidthOrHeight:2048});png=await readData(blob);}all[q.id]={...all[q.id],scene,drawing_png:png};}return all;}
 snapper.current=snapshot;
 function save(action='save'){
  const task=async()=>{const st=current.current;if(st.status!=='draft')return st;setBusy(true);const gen=generation.current;try{const latest=await snapper.current();let saved;
   if(data.offline){const now=Date.now()/1000;saved={...st,answers:latest,revision:st.revision+1,saved_at:now};if(action==='start'&&!saved.started_at)saved.started_at=now;if(action==='pause'){if(saved.pause_started){saved.paused_seconds+=now-saved.pause_started;saved.pause_started=null;}else saved.pause_started=now;}if(action==='submit'){if(saved.pause_started){saved.paused_seconds+=now-saved.pause_started;saved.pause_started=null;}saved.status='submitted';saved.submitted_at=now;saved.elapsed_seconds=Math.max(0,now-saved.started_at-saved.paused_seconds);}localStorage.setItem(key,JSON.stringify(saved));}
   else {const r=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':data.token},body:JSON.stringify({attempt_id:st.attempt_id,revision:st.revision,answers:latest})});const body=await r.json();if(!r.ok)throw new Error(body.error);saved=body;}
   assign(saved);if(generation.current===gen){dirty.current=false;ans.current=saved.answers;setAnswers(saved.answers);}else{const merged={...ans.current};for(const id in latest){if(JSON.stringify(merged[id].scene?.elements)===JSON.stringify(latest[id].scene?.elements))merged[id]={...merged[id],scene:latest[id].scene,drawing_png:latest[id].drawing_png};}ans.current=merged;setAnswers(merged);}setNotice(saved.status==='submitted'?'答卷已冻结。请回到 Agent 点击“已提交”':data.offline?'草稿在浏览器中；尚未写回磁盘':'已保存到本地 · '+new Date(saved.saved_at*1000||Date.now()).toLocaleTimeString());return saved;
  }catch(e){setNotice('保存失败：'+e.message+'。输入保留，可导出备份');throw e;}finally{setBusy(false);}};
  const p=chain.current.catch(()=>{}).then(task);chain.current=p;return p;
 }
 useEffect(()=>{const t=setInterval(()=>{setTick(Date.now()/1000);if(dirty.current&&current.current.status==='draft')save().catch(()=>{});},2000);return()=>{clearInterval(t);};},[q.id,draw]);
 useEffect(()=>{const onexit=e=>{if(dirty.current){e.preventDefault();e.returnValue='尚有未保存作答';}};window.addEventListener('beforeunload',onexit);return()=>window.removeEventListener('beforeunload',onexit);},[]);
 const elapsed=state.started_at?Math.max(0,(state.submitted_at||state.pause_started||tick)-state.started_at-state.paused_seconds):0;
 const remain=state.mode==='timed'&&state.started_at?Math.max(0,state.duration_seconds-(tick-state.started_at)):null;
 useEffect(()=>{if(remain===0&&state.status==='draft')save('submit').catch(()=>{});},[remain,state.status]);
 async function move(n){try{await save();api.current=null;setDraw(false);setIdx(n);}catch{}}
 async function toggleDraw(){try{await save();api.current=null;setDraw(!draw);}catch{}}
 async function attachments(e){try{const items=[];for(const f of e.target.files){if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>8*1024*1024)throw new Error('附件仅接受 8 MB 以内 PNG/JPEG/WebP');items.push({name:f.name,data:await readData(f)});}change({...answers,[q.id]:{...answers[q.id],attachments:[...(answers[q.id].attachments||[]),...items]}});}catch(err){setNotice(err.message);}}
 async function background(fig){const r=await fetch(fig.file);const blob=await r.blob();const url=await readData(blob);const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;canvas.getContext('2d').drawImage(img,0,0);const raster=canvas.toDataURL('image/png');const id=crypto.randomUUID();api.current.addFiles([{id,dataURL:raster,mimeType:'image/png',created:Date.now()}]);const [element]=convertToExcalidrawElements([{type:'image',fileId:id,x:0,y:0,width:img.width,height:img.height,status:'saved',locked:true}]);element.customData={labSource:'question-background',source:fig.file};api.current.updateScene({elements:[element,...api.current.getSceneElements()]});}
 const a=answers[q.id],readonly=state.status!=='draft'||!state.started_at||!!state.pause_started;
 return <><header><div><b>软考作答实验室</b><small>{data.pack.title} · {state.attempt_id}</small></div><div className="timer"><span>{state.mode==='timed'?'剩余':'用时'} {timefmt(remain??elapsed)}</span>{state.status==='draft'&&(!state.started_at?<button onClick={()=>save('start').catch(()=>{})}>开始作答</button>:state.mode==='free'&&<button onClick={()=>save('pause').catch(()=>{})}>{state.pause_started?'继续计时':'暂停'}</button>)}<button onClick={async()=>{try{download(state.attempt_id+'.json',{...current.current,answers:await snapshot()});}catch(e){setNotice('导出失败：'+e.message);}}}>导出{state.status==='draft'?'草稿':'答卷'}</button>{state.status==='draft'&&<button className="primary" disabled={busy||!state.started_at} onClick={()=>setConfirm(true)}>交卷</button>}</div></header>
 <div className="status" role="status">{notice}{backup&&!data.offline&&backup.revision>=state.revision&&JSON.stringify(backup.answers)!==JSON.stringify(state.answers)&&state.status==='draft'&&<button onClick={()=>{change(backup.answers);setNotice('浏览器备份已恢复到输入区，请保存');}}>恢复浏览器未保存稿</button>}</div>
 <div className="workspace"><aside aria-label="案例题导航">{data.pack.cases.map((cc,ci)=><section key={cc.id}><h3>{ci+1}. {cc.title}</h3>{entries.map((entry,i)=>entry.c.id===cc.id&&<button key={entry.q.id} className={idx===i?'selected':''} onClick={()=>move(i)}>{entry.q.title||entry.q.id}<span>{blank(answers[entry.q.id])?'未答':'已作答'}</span></button>)}</section>)}<p>每道包含全部小问。参考解析和评分表由 Agent 私下保管。</p></aside>
 <main className="exam-grid"><article className="question"><div className="eyebrow">{c.source.label} · {c.max_score} 分</div><h1>{c.title}</h1><Markdown text={c.stem}/>{c.figures?.map(f=><figure key={f.file}><img src={f.file} alt={f.caption} onClick={()=>setZoom(f.file)}/><figcaption>{f.caption} · 点击放大</figcaption></figure>)}<h2>{q.title} · {q.max_score} 分</h2><Markdown text={q.prompt}/><details><summary>评分口径</summary><p>{data.pack.scoring_notice} 未提及的必要条件不替你补全。参考估分与严格训练分分别展示，训练分不冒充官方分数。</p></details></article>
 <section className="answer"><div className="answerbar"><h2>作答</h2><button onClick={()=>setPreview(!preview)}>{preview?'编辑正文':'Markdown 预览'}</button><button onClick={toggleDraw}>{draw?'收起绘图':'绘图区'}</button><button disabled={busy||readonly} onClick={()=>save().catch(()=>{})}>保存</button></div>{preview?<Markdown text={a.markdown}/>:<textarea aria-label="小问答案" placeholder="直接输入答案；支持 Markdown、列表、表格、代码和 $公式$。" value={a.markdown} readOnly={readonly} onChange={e=>change({...answers,[q.id]:{...a,markdown:e.target.value}})}/>}
 {draw&&<><p className="hint">箭头、椭圆、圆角矩形和文字；选中后可分组，支持撤销和缩放。{c.figures?.map(f=><button disabled={!api.current||readonly} key={f.file} onClick={()=>background(f).catch(e=>setNotice(e.message))}>题图作底图</button>)}</p><div className="drawing"><Excalidraw key={q.id} langCode="zh-CN" excalidrawAPI={v=>{api.current=v;}} initialData={a.scene||undefined} viewModeEnabled={readonly} UIOptions={{canvasActions:{loadScene:false,saveToActiveFile:false,export:false}}} onChange={(elements,appState,files)=>{if(!readonly){const scene={elements,appState:{viewBackgroundColor:appState.viewBackgroundColor,zoom:appState.zoom,scrollX:appState.scrollX,scrollY:appState.scrollY},files};if(JSON.stringify(scene)!==JSON.stringify(ans.current[q.id]?.scene)){change({...ans.current,[q.id]:{...ans.current[q.id],scene}});}}}}/></div></>}
 {!draw&&a.drawing_png&&<img className="answer-image" src={a.drawing_png} onClick={()=>setZoom(a.drawing_png)}/>}<label className="upload">上传辅助作答图<input disabled={readonly} type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={attachments}/></label><div className="attachments">{a.attachments?.map((f,i)=><figure key={i}><img src={f.data} onClick={()=>setZoom(f.data)}/><figcaption>{f.name} {!readonly&&<button onClick={()=>change({...answers,[q.id]:{...a,attachments:a.attachments.filter((_,j)=>i!==j)}})}>移除</button>}</figcaption></figure>)}</div></section></main></div>
 {confirm&&<div className="dialog" role="dialog" aria-label="确认交卷"><div><h2>确认交卷</h2><p>{entries.filter(e=>blank(answers[e.q.id])).length} 个小问空白。交卷后不能修改；先保存正文、图稿和附件，再冻结。</p><button onClick={()=>setConfirm(false)}>继续作答</button><button className="primary" disabled={busy} onClick={async()=>{try{const s=await save('submit');setConfirm(false);if(data.offline)download(s.attempt_id+'.json',s);}catch{}}}>保存并提交</button></div></div>}<Lightbox src={zoom} close={()=>setZoom(null)}/></>;
}
function Bar({label,value,max,pending}){return <div className="bar"><span>{label}</span><div><i style={{width:`${value/max*100}%`}}/></div><b>{pending?'待核验':`${value} / ${max}`}</b></div>;}
function Report(){const {grade:g,state:s,pack:p}=data;const [zoom,setZoom]=useState(null),[highlight,setHighlight]=useState(null);const qLabel=id=>p.cases.flatMap(c=>c.questions).find(q=>q.id===id)?.title||id;const sourceLevel={'exam-study-book':'考试研究部指定解析','institution-original':'机构原始解析','authored-fixture':'自编验收材料'}[g.answer_source.level]||g.answer_source.level;const dims=Object.entries(g.dimensions);const points=g.results;const counts=Object.values(g.questions).reduce((a,q)=>{for(const k in q.counts)a[k]=(a[k]||0)+q.counts[k];return a;},{});
 return <><header><b>软考作答实验室 · 评阅报告</b><button onClick={()=>window.print()}>打印 / 保存 PDF</button></header><main className="report"><div className="eyebrow">单代理评阅 · {g.basis==='published'?'来源评分细则':'推定训练评分表'} · {sourceLevel} · 用时 {timefmt(g.offline_elapsed_seconds??g.elapsed_seconds)}</div><h1>{p.title}</h1><div className="scores"><article><span>参考估分</span><strong>{g.reference_score??'待核验'}<small> / {g.max_score}</small></strong></article><article><span>严格训练分</span><strong>{g.training_score??'待核验'}<small> / {g.max_score}</small></strong></article><p>训练额外扣分按冻结规则执行，避免同因重复扣罚。该结果描述本次作答，不代表官方阅卷或长期掌握程度。</p></div>
 <section className="charts"><article><h2>小问得分</h2>{Object.entries(g.questions).map(([id,q])=><Bar key={id} label={qLabel(id)} value={q.reference_known} max={q.max} pending={q.pending}/>)}</article><article><h2>采分点分布</h2><div className="distribution">{[['awarded','命中'],['omitted','遗漏'],['incorrect','错误'],['pending','待核验']].map(([k,label])=><div key={k}>{label}<strong>{counts[k]||0}</strong></div>)}</div><h2>本次考点覆盖</h2>{dims.map(([name,v])=><Bar key={name} label={name} value={v.earned} max={v.max} pending={v.pending}/>)}</article></section>
 {dims.length>=3&&!dims.some(([,d])=>d.pending)&&<section><h2>本次考查维度</h2><svg role="img" aria-label="考查维度雷达图" viewBox="0 0 400 300" className="radar">{[.25,.5,.75,1].map(r=><polygon key={r} points={dims.map((_,i)=>{const t=i*2*Math.PI/dims.length-Math.PI/2;return `${200+90*r*Math.cos(t)},${150+90*r*Math.sin(t)}`;}).join(' ')} fill="none" stroke="#b9c8ce"/>)}<polygon points={dims.map(([,v],i)=>{const t=i*2*Math.PI/dims.length-Math.PI/2,r=v.earned/v.max;return `${200+90*r*Math.cos(t)},${150+90*r*Math.sin(t)}`;}).join(' ')} fill="#0e749044" stroke="#0e7490"/>{dims.map(([name],i)=>{const t=i*2*Math.PI/dims.length-Math.PI/2;return <text key={name} x={200+120*Math.cos(t)} y={150+120*Math.sin(t)} textAnchor="middle">{name}</text>;})}</svg></section>}
 {p.cases.map(c=><section key={c.id}><h2>{c.title}</h2><details><summary>完整题干与题图</summary><Markdown text={c.stem}/>{c.figures?.map(f=><figure key={f.file}><img src={f.file} alt={f.caption} onClick={()=>setZoom(f.file)}/><figcaption>{f.caption} · {f.source_locator}</figcaption></figure>)}</details>{c.questions.map(q=>{const a=s.answers[q.id];return <article className="review-question" key={q.id}><h3>{q.title} · 参考 {g.questions[q.id].reference??'待核验'} / {q.max_score} · 训练 {g.questions[q.id].training??'待核验'}</h3><Markdown text={q.prompt}/><div className="review-columns"><div><h4>你的原答卷</h4><pre className="source-answer" id={'answer-'+q.id}>{highlight?.question_id===q.id?<>{[...a.markdown].slice(0,highlight.start).join('')}<mark>{[...a.markdown].slice(highlight.start,highlight.end).join('')}</mark>{[...a.markdown].slice(highlight.end).join('')}</>:a.markdown||'（空白）'}</pre><Markdown text={a.markdown}/>{a.drawing_png&&<img src={a.drawing_png} onClick={()=>setZoom(a.drawing_png)}/>} {a.attachments?.map((f,i)=><img key={i} src={f.data} onClick={()=>setZoom(f.data)}/>)}</div><div><h4>逐点反馈</h4>{points.filter(r=>r.question_id===q.id).map(r=><div key={r.id} className={'point '+r.status}><b>{r.status==='awarded'?'✓ 命中':r.status==='omitted'?'○ 遗漏':r.status==='pending'?'? 待核验':'× 错误'} · {r.earned} / {r.weight} · {r.criterion}</b><Markdown text={r.correct}/><p>{r.comment}</p>{r.evidence?.map((e,i)=><blockquote key={i}>{e.kind==='text'?<button onClick={()=>{setHighlight({...e,question_id:q.id});document.getElementById('answer-'+q.id)?.scrollIntoView({block:'center'});}}>{`定位原文 ${e.start}–${e.end}：“${e.quote}”`}</button>:`图示 ${e.element_id||e.index}：${e.description}`}</blockquote>)}{r.pending_reason&&<p>{r.pending_reason}</p>}</div>)}{g.reference_penalties?.filter(e=>e.question_id===q.id).map((e,i)=><div className="point incorrect" key={'ref'+i}>来源细则扣分：{e.amount} 分<p>{e.comment} · {e.source}</p></div>)}{g.penalties.filter(e=>e.question_id===q.id).map((e,i)=><div className="point incorrect" key={i}>训练扣分：{e.amount} 分{e.deduplicated?'（同因去重）':''}<p>{e.comment}</p></div>)}</div></div></article>;})}</section>)}
 <section><h2>下一步强化</h2>{g.recommendations?.map((r,i)=><article key={i}><h3>{r.priority}. {r.topic}</h3><p>{r.reason}</p><pre>{r.prompt}</pre><button onClick={async()=>{try{await navigator.clipboard.writeText(r.prompt);}catch{window.prompt('复制讲解 prompt',r.prompt);}}}>复制讲解 prompt</button></article>)}</section><details><summary>来源与自检记录</summary><p>{g.answer_source.locator}</p><pre>{JSON.stringify(g.self_check,null,2)}</pre><p>场次 {s.attempt_id} · 评分表 {g.rubric_hash} · 答卷 {g.submission_hash}</p></details></main><Lightbox src={zoom} close={()=>setZoom(null)}/></>;
}
createRoot(document.getElementById('root')).render(data.mode==='report'?<Report/>:<Exam/>);
