import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Excalidraw,exportToBlob,convertToExcalidrawElements} from '@excalidraw/excalidraw';
import '@excalidraw/excalidraw/index.css';
import {Markdown,reviewAnnotations,annotationLabels} from './review-markdown.mjs';
import 'katex/dist/katex.min.css';
import './style.css';
const data=JSON.parse(document.getElementById('lab-data').textContent);
const download=(name,obj)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const readData=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});
const timefmt=n=>`${Math.floor(n/3600).toString().padStart(2,'0')}:${Math.floor(n/60%60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
const blank=a=>!(a.essay?a.essay.abstract.trim()||a.essay.body.trim():a.markdown.trim())&&!(a.scene?.elements||[]).some(e=>!e.isDeleted)&&!a.attachments?.length;
function Lightbox({src,close}){return src&&<div className="lightbox" role="dialog" aria-label="放大图片" onClick={close}><button onClick={close}>关闭</button><img src={src}/></div>;}
const essayMarkdown=parts=>'## 摘要\n\n'+parts.abstract+'\n\n## 正文\n\n'+parts.body;
const charCount=text=>[...text.replace(/\s/g,'')].length;
function PaperRules({pack}){
 const exam=pack.exam;
 if(!exam)return <div className="paper-rules practice">练习模式 · 全部题目计分 · 满分 {pack.cases.reduce((n,c)=>n+c.max_score,0)} 分</div>;
 return <section className="paper-rules" aria-label="试卷作答要求"><div className="paper-heading"><b>{exam.kind==='essay'?'论文':'案例分析'}试卷要求</b><span>满分 {exam.max_score} 分 · 单科合格线 {exam.pass_score} 分{exam.duration_minutes?` · 原卷时长 ${exam.duration_minutes} 分钟`:''}</span></div><Markdown text={exam.instructions}/>{exam.essay_limits&&<p>须分别填写摘要与正文。摘要 {exam.essay_limits.abstract_min?`${exam.essay_limits.abstract_min}–`: '不超过 '}{exam.essay_limits.abstract_max} 字；正文 {exam.essay_limits.body_min}–{exam.essay_limits.body_max} 字。</p>}<details><summary>试卷规则与合格标准出处</summary><Markdown text={exam.rules_source+'\n\n'+exam.pass_source}/></details></section>;
}
function Exam(){
 const key='soft-exam-lab:'+data.state.attempt_id;
 const [backup,setBackup]=useState(()=>{try{return JSON.parse(localStorage.getItem(key));}catch{return null;}});
 const initial=data.offline&&backup?.attempt_id===data.state.attempt_id?backup:data.state;
 const exam=data.pack.exam,isEssay=exam?.kind==='essay',automatic=exam?.selection_policy==='answered-lowest-numbered',required=exam?.required_case_ids||[];
 const initialSelection=initial.selected_case_ids||(exam?required:data.pack.cases.map(c=>c.id));
 const selected=useRef(initialSelection);
 const [choiceSlots,setChoiceSlots]=useState(()=>Array.from({length:exam?.choose_count||0},(_,i)=>initialSelection.filter(id=>!required.includes(id))[i]||''));
 const [state,setState]=useState(initial),[answers,setAnswers]=useState(initial.answers),[idx,setIdx]=useState(()=>isEssay?Math.max(0,data.pack.cases.findIndex(c=>initialSelection.includes(c.id))):0),[preview,setPreview]=useState(false),[draw,setDraw]=useState(false),[notice,setNotice]=useState(data.offline?'离线模式：仅浏览器草稿；交卷后必须导出并由 Agent 导入':'已读取本地记录'),[zoom,setZoom]=useState(null),[tick,setTick]=useState(Date.now()/1000),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
 const entries=data.pack.cases.flatMap(c=>c.questions.map(q=>({c,q}))),{c,q}=entries[idx];
 const current=useRef(state),ans=useRef(answers),api=useRef(null),dirty=useRef(false),chain=useRef(Promise.resolve()),generation=useRef(0),snapper=useRef(null),undoStack=useRef({}),composition=useRef(null),choiceRef=useRef(choiceSlots);
 current.current=state;ans.current=answers;choiceRef.current=choiceSlots;
 const assign=s=>{current.current=s;setState(s);};
 const change=a=>{dirty.current=true;generation.current++;ans.current=a;setAnswers(a);try{localStorage.setItem(key,JSON.stringify({...current.current,selected_case_ids:selected.current,answers:a}));}catch{setNotice('浏览器备份空间不足；请保存或导出输入');}};
 const remember=(qid,value)=>{const history=undoStack.current[qid]||=[];history.push(value);if(history.length>20)history.shift();};
 const editableText=a=>a.essay?{...a.essay}:a.markdown;
 function withText(a,text,field){if(field==='markdown')return {...a,markdown:text};const parts={...a.essay,[field]:text};return {...a,essay:parts,markdown:essayMarkdown(parts)};}
 function editText(text,field='markdown'){const before=ans.current[q.id];if(text===(field==='markdown'?before.markdown:before.essay[field]))return;if(!composition.current)remember(q.id,editableText(before));change({...ans.current,[q.id]:withText(before,text,field)});}
 function endComposition(text,field){const edit=composition.current;composition.current=null;const qid=edit?.qid||q.id;if(edit&&JSON.stringify(edit.before)!==JSON.stringify(editableText(withText(ans.current[qid],text,field))))remember(qid,edit.before);change({...ans.current,[qid]:withText(ans.current[qid],text,field)});}
 function undoText(){const value=undoStack.current[q.id]?.pop();if(value!==undefined){const previous=ans.current[q.id];change({...ans.current,[q.id]:typeof value==='string'?{...previous,markdown:value}:{...previous,essay:value,markdown:essayMarkdown(value)}});}}
 async function choose(slot,value){try{if(draw)await save();const next=[...choiceRef.current];next[slot]=value;choiceRef.current=next;selected.current=[...required,...next.filter(Boolean)];setChoiceSlots(next);change({...ans.current});if(isEssay&&value){api.current=null;setDraw(false);setIdx(entries.findIndex(e=>e.c.id===value));}}catch{}}
 async function restoreBackup(){setBusy(true);try{const restored={...backup.answers};for(const id in restored){const a=restored[id];if(a.scene?.elements.some(e=>!e.isDeleted)){const blob=await exportToBlob({elements:a.scene.elements,appState:{...a.scene.appState,exportBackground:true},files:a.scene.files,mimeType:'image/png',maxWidthOrHeight:2048});restored[id]={...a,drawing_png:await readData(blob)};}}const ids=backup.selected_case_ids||initialSelection;selected.current=ids;setChoiceSlots(Array.from({length:exam?.choose_count||0},(_,i)=>ids.filter(id=>!required.includes(id))[i]||''));api.current=null;setDraw(false);if(isEssay)setIdx(Math.max(0,entries.findIndex(e=>ids.includes(e.c.id))));change(restored);setBackup(null);setNotice('浏览器备份已恢复到输入区，请保存');}catch(e){setNotice('备份恢复失败：'+e.message+'。原输入保留');}finally{setBusy(false);}}
 const selectionReady=automatic||!exam||(selected.current.length===required.length+exam.choose_count&&new Set(selected.current).size===selected.current.length);
 async function snapshot(){const all={...ans.current};const view=api.current;if(view&&draw){const elements=view.getSceneElements();const appState=view.getAppState();const files=view.getFiles();const scene={elements,appState:{viewBackgroundColor:appState.viewBackgroundColor,zoom:appState.zoom,scrollX:appState.scrollX,scrollY:appState.scrollY},files};let png=null;if(elements.some(e=>!e.isDeleted)){const blob=await exportToBlob({elements,appState:{...appState,exportBackground:true},files,mimeType:'image/png',maxWidthOrHeight:2048});png=await readData(blob);}all[q.id]={...all[q.id],scene,drawing_png:png};}return all;}
 snapper.current=snapshot;
 function save(action='save'){
  const task=async()=>{const st=current.current;if(st.status!=='draft')return st;setBusy(true);const gen=generation.current;try{
   const ids=[...selected.current];if(exam&&!automatic&&(action==='start'||action==='submit'||st.started_at)&&ids.length!==required.length+exam.choose_count)throw new Error('请按试卷要求选齐计分题目');
   const latest=await snapper.current();let saved;
   if(data.offline){const now=Date.now()/1000;saved={...st,selected_case_ids:ids,answers:latest,revision:st.revision+1,saved_at:now};if(action==='start'&&!saved.started_at)saved.started_at=now;if(action==='pause'){if(saved.pause_started){saved.paused_seconds+=now-saved.pause_started;saved.pause_started=null;}else saved.pause_started=now;}if(action==='submit'){if(saved.pause_started){saved.paused_seconds+=now-saved.pause_started;saved.pause_started=null;}saved.status='submitted';saved.submitted_at=now;saved.elapsed_seconds=Math.max(0,now-saved.started_at-saved.paused_seconds);}localStorage.setItem(key,JSON.stringify(saved));}
   else{const r=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':data.token},body:JSON.stringify({attempt_id:st.attempt_id,revision:st.revision,selected_case_ids:ids,answers:latest})});const body=await r.json();if(!r.ok)throw new Error(body.error);saved=body;}
   assign(saved);if(generation.current===gen){dirty.current=false;ans.current=saved.answers;setAnswers(saved.answers);}else{const merged={...ans.current};for(const id in latest){if(JSON.stringify(merged[id].scene?.elements)===JSON.stringify(latest[id].scene?.elements))merged[id]={...merged[id],scene:latest[id].scene,drawing_png:latest[id].drawing_png};}ans.current=merged;setAnswers(merged);}setNotice(saved.status==='submitted'?'答卷已冻结。请回到 Agent 点击“已提交”':data.offline?'草稿在浏览器中；尚未写回磁盘':'已保存到本地 · '+new Date(saved.saved_at*1000||Date.now()).toLocaleTimeString());return saved;
  }catch(e){setNotice('保存失败：'+e.message+'。输入保留，可导出备份');throw e;}finally{setBusy(false);}};
  const p=chain.current.catch(()=>{}).then(task);chain.current=p;return p;
 }
 useEffect(()=>{const t=setInterval(()=>{setTick(Date.now()/1000);if(dirty.current&&current.current.status==='draft')save().catch(()=>{});},2000);return()=>clearInterval(t);},[q.id,draw]);
 useEffect(()=>{const onexit=e=>{if(dirty.current){e.preventDefault();e.returnValue='尚有未保存作答';}};window.addEventListener('beforeunload',onexit);return()=>window.removeEventListener('beforeunload',onexit);},[]);
 const elapsed=state.started_at?Math.max(0,(state.submitted_at||state.pause_started||tick)-state.started_at-state.paused_seconds):0;
 const remain=state.mode==='timed'&&state.started_at?Math.max(0,state.duration_seconds-(tick-state.started_at)):null;
 useEffect(()=>{if(remain===0&&state.status==='draft')save('submit').catch(()=>{});},[remain,state.status]);
 async function move(n){try{await save();api.current=null;setDraw(false);setIdx(n);}catch{}}
 async function toggleDraw(){try{await save();api.current=null;setDraw(!draw);}catch{}}
 async function attachments(e){try{const items=[];for(const f of e.target.files){if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>8*1024*1024)throw new Error('附件仅接受 8 MB 以内 PNG/JPEG/WebP');items.push({name:f.name,data:await readData(f)});}change({...ans.current,[q.id]:{...ans.current[q.id],attachments:[...(ans.current[q.id].attachments||[]),...items]}});}catch(err){setNotice(err.message);}}
 async function background(fig){const r=await fetch(fig.file);const blob=await r.blob();const url=await readData(blob);const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;canvas.getContext('2d').drawImage(img,0,0);const raster=canvas.toDataURL('image/png');const id=crypto.randomUUID();api.current.addFiles([{id,dataURL:raster,mimeType:'image/png',created:Date.now()}]);const [element]=convertToExcalidrawElements([{type:'image',fileId:id,x:0,y:0,width:img.width,height:img.height,status:'saved',locked:true}]);element.customData={labSource:'question-background',source:fig.file};api.current.updateScene({elements:[element,...api.current.getSceneElements()]});}
 const a=answers[q.id],counted=automatic||selected.current.includes(c.id),readonly=state.status!=='draft'||!state.started_at||!!state.pause_started||!counted;
 const compositionProps=field=>({onCompositionStart:()=>{composition.current={qid:q.id,before:editableText(ans.current[q.id])};},onCompositionEnd:e=>endComposition(e.currentTarget.value,field)});
 const countedEntries=entries.filter(e=>selected.current.includes(e.c.id));
 return <><header><div><b>软考作答实验室</b><small>{data.pack.title} · {state.attempt_id}</small></div><div className="timer"><span>{state.mode==='timed'?'剩余':'用时'} {timefmt(remain??elapsed)}</span>{state.status==='draft'&&(!state.started_at?<button disabled={busy||!selectionReady} onClick={()=>save('start').catch(()=>{})}>开始作答</button>:state.mode==='free'&&<button onClick={()=>save('pause').catch(()=>{})}>{state.pause_started?'继续计时':'暂停'}</button>)}<button onClick={async()=>{try{download(state.attempt_id+'.json',{...current.current,selected_case_ids:[...selected.current],answers:await snapshot()});}catch(e){setNotice('导出失败：'+e.message);}}}>导出{state.status==='draft'?'草稿':'答卷'}</button>{state.status==='draft'&&<button className="primary" disabled={busy||!state.started_at||!selectionReady} onClick={()=>setConfirm(true)}>交卷</button>}</div></header>
 <div className="status" role="status">{notice}{backup&&!data.offline&&backup.revision>=state.revision&&(JSON.stringify(backup.answers)!==JSON.stringify(state.answers)||JSON.stringify(backup.selected_case_ids||initialSelection)!==JSON.stringify(state.selected_case_ids||initialSelection))&&state.status==='draft'&&<button disabled={busy} onClick={restoreBackup}>恢复浏览器未保存稿</button>}</div>
 <PaperRules pack={data.pack}/>
 {automatic&&<section className="paper-selection" aria-label="自动计分规则"><b>按已作答题自动计分</b><p>必答题始终计入；选答题按题号从小到大取前 {exam.choose_count} 道已答题。多答题会单独批改，不计入总分。无需手动勾选。</p></section>}{exam&&!automatic&&<section className="paper-selection" aria-label="选择计分题目"><div>{required.length>0&&<span>必答：{data.pack.cases.filter(c=>required.includes(c.id)).map(c=>c.title).join('、')}</span>}<b>已选 {choiceSlots.filter(Boolean).length} / {exam.choose_count} 道选答题</b></div>{choiceSlots.map((value,i)=><label key={i}>{isEssay?'论文选题':`选答题 ${i+1}`}<select aria-label={isEssay?'论文选题':`选答题 ${i+1}`} value={value} disabled={state.status!=='draft'} onChange={e=>choose(i,e.target.value)}><option value="" disabled={!!state.started_at}>请选择</option>{data.pack.cases.filter(c=>!required.includes(c.id)).map(c=><option key={c.id} value={c.id} disabled={choiceSlots.some((v,j)=>j!==i&&v===c.id)}>{c.title}</option>)}</select></label>)}<small>可查看全部题目；仅选中的题目计分。切换选题会保留已有草稿。</small></section>}
 <div className="workspace"><aside aria-label={isEssay?'论文题导航':'案例题导航'}>{data.pack.cases.map((cc,ci)=><section key={cc.id}><h3>{ci+1}. {cc.title}</h3>{exam&&<span className={'case-tag '+(selected.current.includes(cc.id)?'counted':'')}>{required.includes(cc.id)?'必答':automatic?'按题号自动计分':selected.current.includes(cc.id)?'计分':'未选'}</span>}{entries.map((entry,i)=>entry.c.id===cc.id&&<button key={entry.q.id} className={idx===i?'selected':''} onClick={()=>move(i)}>{entry.q.title||entry.q.id}<span>{blank(answers[entry.q.id])?'未答':'已作答'}</span></button>)}</section>)}<p>参考解析和评分表在提交后用于评阅。</p></aside>
 <main className="exam-grid"><article className="question"><div className="eyebrow">{c.source.label} · {c.max_score} 分</div><h1>{c.title}</h1><Markdown text={c.stem}/>{c.figures?.map(f=><figure key={f.file}><img src={f.file} alt={f.caption} onClick={()=>setZoom(f.file)}/><figcaption>{f.caption} · 点击放大</figcaption></figure>)}<h2>{q.title} · {q.max_score} 分</h2><Markdown text={q.prompt}/><details><summary>评分口径</summary><p>{data.pack.scoring_notice} 参考估分与严格训练分分别展示。</p></details></article>
 <section className="answer"><section className="answer-prompt" aria-label="当前小问"><h2>{q.title} · {q.max_score} 分</h2><Markdown text={q.prompt}/></section><div className="answerbar"><h2>作答</h2><button onClick={()=>setPreview(!preview)}>{preview?'编辑正文':'Markdown 预览'}</button><button onClick={toggleDraw}>{draw?'收起绘图':'绘图区'}</button><button disabled={busy||readonly} onClick={()=>save().catch(()=>{})}>保存</button><button title="撤销当前小问的正文编辑（最多20次）" disabled={readonly||!undoStack.current[q.id]?.length} onClick={undoText}>撤销</button></div>{!counted&&<p className="selection-hint">本题未选入本次计分，选择后即可作答。</p>}{preview?<Markdown text={a.markdown}/>:isEssay?<div className="essay-editor">{[['abstract','摘要'],['body','正文']].map(([field,label])=><label key={field}>{label}<small>{charCount(a.essay[field])} 字（不含空白）</small><textarea aria-label={label} className={'essay-'+field} value={a.essay[field]} placeholder={field==='abstract'?'概括论文主题、项目背景与主要工作。':'按题目要求展开论述，结合项目说明方法、实施和结果。'} readOnly={readonly} onChange={e=>editText(e.target.value,field)} {...compositionProps(field)}/></label>)}</div>:<textarea aria-label="小问答案" placeholder="直接输入答案；支持 Markdown、列表、表格、代码和 $公式$。" value={a.markdown} readOnly={readonly} onChange={e=>editText(e.target.value)} {...compositionProps('markdown')}/>}
 {draw&&<><p className="hint">图形、箭头和文字；可撤销、缩放。{c.figures?.map(f=><button disabled={!api.current||readonly} key={f.file} onClick={()=>background(f).catch(e=>setNotice(e.message))}>题图作底图</button>)}</p><div className="drawing"><Excalidraw key={q.id} langCode="zh-CN" excalidrawAPI={v=>{api.current=v;}} initialData={a.scene||undefined} viewModeEnabled={readonly} UIOptions={{canvasActions:{loadScene:false,saveToActiveFile:false,export:false}}} onChange={(elements,appState,files)=>{if(!readonly){const scene={elements,appState:{viewBackgroundColor:appState.viewBackgroundColor,zoom:appState.zoom,scrollX:appState.scrollX,scrollY:appState.scrollY},files};if(JSON.stringify(scene)!==JSON.stringify(ans.current[q.id]?.scene)){change({...ans.current,[q.id]:{...ans.current[q.id],scene}});}}}}/></div></>}
 {!draw&&a.drawing_png&&<img className="answer-image" src={a.drawing_png} onClick={()=>setZoom(a.drawing_png)}/>}<label className="upload">上传辅助作答图<input disabled={readonly} type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={attachments}/></label><div className="attachments">{a.attachments?.map((f,i)=><figure key={i}><img src={f.data} onClick={()=>setZoom(f.data)}/><figcaption>{f.name} {!readonly&&<button onClick={()=>change({...ans.current,[q.id]:{...ans.current[q.id],attachments:a.attachments.filter((_,j)=>i!==j)}})}>移除</button>}</figcaption></figure>)}</div></section></main></div>
 {confirm&&<div className="dialog" role="dialog" aria-label="确认交卷"><div><h2>确认交卷</h2><p>本次满分 {exam?.max_score??data.pack.cases.reduce((n,c)=>n+c.max_score,0)} 分。</p>{automatic?<p>必答题始终计入；按已作答题号从小到大取前 {exam.choose_count} 道选答题。多答题单列批改，不计入总分；少答的分值保留在满分中。</p>:<p>计分题目：{data.pack.cases.filter(c=>selected.current.includes(c.id)).map(c=>c.title).join('；')}。{countedEntries.filter(e=>blank(answers[e.q.id])).length} 个计分小问空白。</p>}<p>交卷后答卷与选题一并冻结。</p><button onClick={()=>setConfirm(false)}>继续作答</button><button className="primary" disabled={busy||!selectionReady} onClick={async()=>{try{const s=await save('submit');setConfirm(false);if(data.offline)download(s.attempt_id+'.json',s);}catch{}}}>保存并提交</button></div></div>}<Lightbox src={zoom} close={()=>setZoom(null)}/></>;
}
function Bar({label,value,max,pending}){return <div className="bar"><span>{label}</span><div><i style={{width:`${value/max*100}%`}}/></div><b>{pending?'待核验':`${value} / ${max}`}</b></div>;}
function ResultSummary({pack,grade:g}){
 const outcome=g.exam_outcome,weak=g.weaknesses;
 const name=id=>{for(const c of pack.cases){const q=c.questions.find(q=>q.id===id);if(q)return c.title+' · '+q.title;}return id;};
 const topQuestions=weak?.questions.filter(q=>q.lost>0).slice(0,3)||[];
 const topDimensions=weak?.dimensions.filter(d=>d.lost>0).slice(0,3)||[];
 return <><PaperRules pack={pack}/>{pack.exam?.selection_policy==='answered-lowest-numbered'&&<section className="paper-rules" aria-label="实际计分范围"><p><b>计入总分：</b>{pack.cases.filter(c=>g.selected_case_ids.includes(c.id)).map(c=>c.title).join('；')}。</p>{g.supplemental_case_ids?.length>0&&<p>多答题单列批改，不计入总分、得分图表或主要失分排行。</p>}{g.unanswered_score>0&&<p>尚有 {g.unanswered_score} 分的选答题未作答，试卷满分保持 {g.max_score} 分。</p>}</section>}{outcome&&<section className={'exam-outcome '+outcome.status} aria-label="及格判定"><strong>{outcome.status==='pass'?'及格':outcome.status==='fail'?'不及格':'待核验'}</strong><p>{outcome.status==='pending'?'存在待核验采分点，暂不判定。':`参考估分 ${g.reference_score} / ${outcome.max_score}；单科合格线 ${outcome.pass_score} 分。`} 此处按参考估分对照合格线。{outcome.status==='fail'&&<>距合格线还差 {outcome.pass_score-g.reference_score} 分。</>}</p></section>}{weak&&<section className="weakness-summary" aria-label="主要失分位置"><h2>哪里失分最多{weak.known_only?'（已核验部分）':''}</h2>{topQuestions.length===0?<p>已核验采分点没有失分。</p>:<div className="weakness-columns"><div><h3>小问</h3><ol>{topQuestions.map(q=><li key={q.question_id}><b>{name(q.question_id)}</b><span>失分 {q.lost} / {q.max_score} · 错误 {q.incorrect} 项 · 遗漏 {q.omitted} 项</span></li>)}</ol></div><div><h3>考点</h3><ol>{topDimensions.map(d=><li key={d.name}><b>{d.name}</b><span>失分 {d.lost} / {d.max} · 错误 {d.incorrect} 项 · 遗漏 {d.omitted} 项</span></li>)}</ol></div></div>}</section>}</>;
}
function ReferenceAnswer({reference,essayReview,zoom}){
 return <>{essayReview&&<section className="essay-review"><h4>审题要求对照</h4>{[['abstract','摘要'],['body','正文']].map(([field,label])=><p key={field}>{label}：{essayReview.counts[field]} 字（不含空白）；题卷要求 {essayReview.limits[field+'_min']?`${essayReview.limits[field+'_min']}–`:'不超过 '}{essayReview.limits[field+'_max']} 字，<b>{essayReview.within_limits[field]?'符合字数要求':'未满足字数或内容非空要求'}</b>。</p>)}<ul>{essayReview.requirements.map(t=><li key={t.id}><b>{({'met':'已覆盖','partial':'部分覆盖','not-met':'未覆盖','pending':'待核验'})[t.status]}</b> · {t.text}</li>)}</ul></section>}<section className="reference-answer" aria-label={essayReview?'应试参考范文':'参考答案'}><h4>{essayReview?'应试参考范文':'参考答案'}{reference?.origin==='skill-generated'?' · Skill 整理生成':reference?.origin==='pending'?' · 待核验':''}</h4>{reference?<><Markdown text={reference.markdown}/>{reference.images?.map((f,i)=><figure key={i}><img src={f.data} alt={f.caption} onClick={()=>zoom(f.data)}/><figcaption>{f.caption}</figcaption></figure>)}<div className="reference-source"><Markdown text={'依据：'+reference.source}/></div></>:<p>这份历史报告尚未保存完整参考答案，可使用当前 Skill 补充评阅。</p>}</section></>;
}
function EvidenceQuote({e,annotation,locate}){
 if(e.kind!=='text')return <blockquote>图示 {e.element_id||e.index}：{e.description}</blockquote>;
 const chars=[...e.quote],spans=annotation?.spans||[];
 const cuts=[...new Set([0,chars.length,...spans.flatMap(s=>[s.start-e.start,s.end-e.start])])].sort((a,b)=>a-b);
 return <blockquote><button className="evidence-jump" onClick={()=>locate(annotation?.id)}><span className="evidence-heading">{annotationLabels[annotation?.tone]||'原文证据'}<small>点击定位</small></span><span className="evidence-text">{cuts.slice(0,-1).map((from,i)=>{const to=cuts[i+1],text=chars.slice(from,to).join('');return spans.some(s=>s.start-e.start<to&&s.end-e.start>from)?<mark key={from} className={'review-mark review-'+annotation.tone}>{text}</mark>:<React.Fragment key={from}>{text}</React.Fragment>;})}</span></button></blockquote>;
}
function QuestionReview({q,a,g,highlight,setHighlight,setZoom}){
 const annotations=reviewAnnotations(g,q.id);
 const locate=id=>{
  setHighlight(id);
  const answer=document.getElementById('annotated-'+q.id);
  const mark=Array.from(answer?.querySelectorAll('[data-review-ids]')||[]).find(el=>el.dataset.reviewIds.split(' ').includes(id));
  (mark||answer)?.scrollIntoView({block:'center'});
 };
 return <article className="review-question">
  <h3>{q.title} · 参考 {g.questions[q.id].reference??'待核验'} / {q.max_score} · 训练 {g.questions[q.id].training??'待核验'}</h3>
  <Markdown text={q.prompt}/>
  <div className="review-columns"><div>
   <h4>你的原答卷</h4>
   <div className="annotation-legend" aria-label="批注颜色说明"><span><mark className="review-mark review-good">绿色</mark> 得分</span><span><mark className="review-mark review-risk">黄色</mark> 表述风险</span><span><mark className="review-mark review-error">红色</mark> 明确错误</span><small>无填充：未批注。黄色不额外扣分；红色的计分影响见右侧反馈。</small></div>
   <details className="raw-answer"><summary>查看原始 Markdown</summary><pre className="source-answer">{a.markdown||'（空白）'}</pre></details>
   <div className="annotated-answer" id={'annotated-'+q.id}><Markdown text={a.markdown||'（空白）'} annotations={annotations} activeId={highlight}/></div>
   {a.drawing_png&&<img src={a.drawing_png} onClick={()=>setZoom(a.drawing_png)}/>}
   {a.attachments?.map((f,i)=><img key={i} src={f.data} onClick={()=>setZoom(f.data)}/>)}
   <ReferenceAnswer reference={g.reference_answers?.[q.id]} essayReview={g.essay_review?.[q.id]} zoom={setZoom}/>
  </div><div><h4>逐点反馈</h4>
   {g.results.filter(r=>r.question_id===q.id).map(r=><div key={r.id} className={'point '+r.status}>
    <b>{r.status==='awarded'?'✓ 命中':r.status==='omitted'?'○ 遗漏':r.status==='pending'?'? 待核验':'× 错误'} · {r.earned} / {r.weight} · {r.criterion}</b>
    <Markdown text={r.correct}/><p>{r.comment}</p>
    {r.evidence?.map((e,i)=><EvidenceQuote key={i} e={e} annotation={annotations.find(a=>a.id==='point-'+r.id+'-'+i)} locate={locate}/>)}
    {r.pending_reason&&<p>{r.pending_reason}</p>}
   </div>)}
   {[['warnings','risk','△ 表述风险 · 不额外扣分'],['reference_penalties','incorrect','来源细则扣分'],['penalties','incorrect','训练扣分']].map(([field,style,label])=>g[field]?.map((e,i)=>e.question_id===q.id&&<div className={'point '+style} key={field+i}>
    <b>{label}{field!=='warnings'&&<>：{e.amount} 分{e.deduplicated?'（同因去重）':''}</>}</b><p>{e.comment}</p>
    {e.evidence&&<EvidenceQuote e={e.evidence} annotation={annotations.find(a=>a.id===field+'-'+i)} locate={locate}/>}
    {e.source&&<small className="feedback-source">依据：{e.source}</small>}
   </div>))}
  </div></div>
 </article>;
}
function Report(){const {grade:g,state:s,pack:p}=data;const [zoom,setZoom]=useState(null),[highlight,setHighlight]=useState(null);const qLabel=id=>{for(const c of p.cases){const q=c.questions.find(q=>q.id===id);if(q)return c.title+' · '+q.title;}return id;};const sourceLevel={'exam-study-book':'考试研究部指定解析','institution-original':'机构原始解析','authored-fixture':'自编验收材料'}[g.answer_source.level]||g.answer_source.level;const dims=Object.entries(g.dimensions);const counts=Object.values(g.questions).filter(q=>q.counted!==false).reduce((a,q)=>{for(const k in q.counts)a[k]=(a[k]||0)+q.counts[k];return a;},{});
 return <><header><b>软考作答实验室 · 评阅报告</b><button onClick={()=>window.print()}>打印 / 保存 PDF</button></header><main className="report"><div className="eyebrow">单代理评阅 · {g.basis==='published'?'来源评分细则':'推定训练评分表'} · {sourceLevel} · 用时 {timefmt(g.offline_elapsed_seconds??g.elapsed_seconds)}</div><h1>{p.title}</h1><ResultSummary pack={p} grade={g}/><div className="scores"><article><span>参考估分</span><strong>{g.reference_score??'待核验'}<small> / {g.max_score}</small></strong></article><article><span>严格训练分</span><strong>{g.training_score??'待核验'}<small> / {g.max_score}</small></strong></article><p>训练额外扣分按冻结规则执行，避免同因重复扣罚。该结果描述本次作答，不代表官方阅卷或长期掌握程度。</p></div>
 <section className="charts"><article><h2>小问得分</h2>{Object.entries(g.questions).filter(([,q])=>q.counted!==false).map(([id,q])=><Bar key={id} label={qLabel(id)} value={q.reference_known} max={q.max} pending={q.pending}/>)}</article><article><h2>采分点分布</h2><div className="distribution">{[['awarded','命中'],['omitted','遗漏'],['incorrect','错误'],['pending','待核验']].map(([k,label])=><div key={k}>{label}<strong>{counts[k]||0}</strong></div>)}</div><h2>本次考点覆盖</h2>{dims.map(([name,v])=><Bar key={name} label={name} value={v.earned} max={v.max} pending={v.pending}/>)}</article></section>
 {dims.length>=3&&!dims.some(([,d])=>d.pending)&&<section><h2>本次考查维度</h2><svg role="img" aria-label="考查维度雷达图" viewBox="0 0 400 300" className="radar">{[.25,.5,.75,1].map(r=><polygon key={r} points={dims.map((_,i)=>{const t=i*2*Math.PI/dims.length-Math.PI/2;return `${200+90*r*Math.cos(t)},${150+90*r*Math.sin(t)}`;}).join(' ')} fill="none" stroke="#b9c8ce"/>)}<polygon points={dims.map(([,v],i)=>{const t=i*2*Math.PI/dims.length-Math.PI/2,r=v.earned/v.max;return `${200+90*r*Math.cos(t)},${150+90*r*Math.sin(t)}`;}).join(' ')} fill="#0e749044" stroke="#0e7490"/>{dims.map(([name],i)=>{const t=i*2*Math.PI/dims.length-Math.PI/2;return <text key={name} x={200+120*Math.cos(t)} y={150+120*Math.sin(t)} textAnchor="middle">{name}</text>;})}</svg></section>}
 {g.supplemental_case_ids?.length>0&&<section className="paper-rules" aria-label="多答题得分"><h2>多答题 · 不计入总分</h2>{p.cases.filter(c=>g.supplemental_case_ids.includes(c.id)).map(c=>{const values=c.questions.map(q=>g.questions[q.id]);return <p key={c.id}>{c.title}：参考 {values.some(q=>q.pending)?'待核验':values.reduce((n,q)=>n+q.reference,0)} / {c.max_score}；训练 {values.some(q=>q.pending)?'待核验':values.reduce((n,q)=>n+q.training,0)}。详细批改见下方。</p>;})}</section>}
 {p.cases.filter(c=>(g.reviewed_case_ids||g.selected_case_ids||p.cases.map(c=>c.id)).includes(c.id)).map(c=><section key={c.id}><h2>{c.title}{g.supplemental_case_ids?.includes(c.id)&&' · 补充批改，不计入总分'}</h2><details><summary>完整题干与题图</summary><Markdown text={c.stem}/>{c.figures?.map(f=><figure key={f.file}><img src={f.file} alt={f.caption} onClick={()=>setZoom(f.file)}/><figcaption>{f.caption} · {f.source_locator}</figcaption></figure>)}</details>{c.questions.filter(q=>g.questions[q.id]).map(q=><QuestionReview key={q.id} q={q} a={s.answers[q.id]} g={g} highlight={highlight} setHighlight={setHighlight} setZoom={setZoom}/>)}</section>)}
 <section><h2>下一步强化</h2>{g.recommendations?.map((r,i)=><article key={i}><h3>{r.priority}. {r.topic}</h3><p>{r.reason}</p><pre>{r.prompt}</pre><button onClick={async()=>{try{await navigator.clipboard.writeText(r.prompt);}catch{window.prompt('复制讲解 prompt',r.prompt);}}}>复制讲解 prompt</button></article>)}</section><details><summary>来源与自检记录</summary><p>{g.answer_source.locator}</p><pre>{JSON.stringify(g.self_check,null,2)}</pre><p>场次 {s.attempt_id} · 评分表 {g.rubric_hash} · 答卷 {g.submission_hash}</p></details></main><Lightbox src={zoom} close={()=>setZoom(null)}/></>;
}
createRoot(document.getElementById('root')).render(data.mode==='report'?<Report/>:<Exam/>);
